//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public int IDProduit { get; set; }
        public string DenominationProduit { get; set; }
        public string CategorieProduit { get; set; }
        public double QuantiteProduit { get; set; }
        public double PUProduit { get; set; }
    }
}
